[breaking] Remove deprecated stuff
eBay/ebayui-core-react pull request #117
Opened 2022-10-07 14:55 UTC by darkwebdev

Fixes #66

2022-10-10 17:54 UTC, abiyasa requested changes
Unfortunately you forgot to remove (as stated at https://github.com/eBay/ebayui-core-react/issues/66):

- EbayProgressStep props `number`, which is replaced by property `state`.

2022-10-10 21:46 UTC, HenriqueLimas commented
@abiyasa this is being done on #114

2022-10-10 21:46 UTC, HenriqueLimas approved these changes

2022-10-11 08:39 UTC, abiyasa approved these changes

2022-10-11 22:54 UTC, merged