Pagination show-last variant overflow button click disabled
eBay/ebayui-core-react pull request #180
Opened 2022-12-15 15:18 UTC by flakronkadriu

- Fix on dots not clickable for "show-last" variation

2022-12-15 18:28 UTC, don-siu commented on src/ebay-pagination/pagination.tsx
> -                onPrevious, onNext, onSelect, a11yPreviousText, a11yNextText,
Not blocker: Is this order matter?

2022-12-15 19:52 UTC, darkwebdev requested changes
I works fine, but I think we don't need to introduce `role` when we already have `type`. Just extend this union type with `separator` or `ellipsys` or `dots` etc and add another switch-case to pagination-item.

2022-12-27 11:33 UTC, flakronkadriu commented on src/ebay-pagination/pagination.tsx
> -                onPrevious, onNext, onSelect, a11yPreviousText, a11yNextText,
No not really, i can revert this change

2022-12-27 14:06 UTC, darkwebdev approved these changes

2022-12-27 14:07 UTC, merged