[FEAT] EbayListboxButton: Adding missing tabIndex functionality from marko component
eBay/ebayui-core-react pull request #194
Opened 2023-01-11 17:19 UTC by marcial199545

Adding missing functionality to have dynamic `tabIndex` with value `0`when list is open and `-1` when it is closed.
https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-listbox/index.marko#:~:text=tabindex%3D(option.disabled%20%3F%20%2D1%20%3A%20option.tabindex)

2023-01-16 12:43 UTC, darkwebdev commented
Hello! Thanks for the PR! I'm trying to understand which problem are we solving here?
[Skin](https://opensource.ebay.com/skin/#listbox-button) always has `tabIndex=0`
[Marko](https://opensource.ebay.com/ebayui-core/?path=/story/buttons-ebay-listbox-button--standard) switches between 0 and -1
But is there a difference from a11y perspective? I thought that if menu is hidden then tabIndex doesn't matter...

2023-01-16 12:49 UTC, darkwebdev requested changes

2023-01-16 12:49 UTC, darkwebdev commented on src/ebay-listbox-button/listbox-button.tsx
> +                        tabIndex={listContainerTabIndex}
```suggestion
                        tabIndex={expanded ? 0 : -1}
```
and you don't need any more changes from above

2023-01-17 03:36 UTC, marcial199545 commented
retest

2023-01-17 04:16 UTC, marcial199545 commented
closing PR, to reopen it with changes proposed by [Timur Manyanov](https://github.com/darkwebdev)

2023-01-17 04:16 UTC, closed without merging