308: Add skeleton loading component
eBay/ebayui-core-react pull request #378
Opened 2024-12-12 00:35 UTC by aaron-nance

Need to do more work with storybook and see what tests to add, but the code is here and mimics what was done in the Marko versions.

2024-12-12 00:39 UTC, aaron-nance commented on src/ebay-skeleton/nativeTags.ts
> +export type NativeTags =
This is based on Marko.NativeTags

2024-12-12 02:19 UTC, shpandian commented on src/ebay-skeleton/ebay-skeleton-avatar.tsx
> +import React, { ComponentProps, FC } from 'react'
seems like valid concern.

2024-12-12 05:30 UTC, shpandian commented on src/ebay-skeleton/ebay-skeleton-textbox.tsx
> +const EbaySkeletonText: FC<Props> = ({
should be EbaySkeletonTextbox?

2024-12-12 15:32 UTC, HenriqueLimas commented on src/ebay-skeleton/ebay-skeleton-avatar.tsx
> +import React, { ComponentProps, FC } from 'react'
eslint should have got this, we need to understand why not

2024-12-12 15:49 UTC, HenriqueLimas requested changes

2024-12-12 15:49 UTC, HenriqueLimas commented on src/ebay-skeleton/ebay-skeleton-avatar.tsx
> +import { NativeTags } from './nativeTags'
We should use the react type instead:

```
    as?: keyof React.JSX.IntrinsicElements;
```

But I think skin supports `div` and `span` only

2024-12-12 15:49 UTC, HenriqueLimas commented on src/ebay-skeleton/ebay-skeleton-button.tsx
> +    <div
It needs to support the `as` also

2024-12-12 15:49 UTC, HenriqueLimas commented on src/ebay-skeleton/ebay-skeleton-image.tsx
> +    <div
It needs to support `as` also

2024-12-12 15:49 UTC, HenriqueLimas commented on src/ebay-skeleton/ebay-skeleton-text.tsx
> +    <div
It needs to support `as` also

2025-02-04 01:24 UTC, HenriqueLimas commented on src/ebay-skeleton/nativeTags.ts
> +export type NativeTags =
Fixed

2025-02-04 01:24 UTC, HenriqueLimas commented on src/ebay-skeleton/ebay-skeleton-textbox.tsx
> +const EbaySkeletonText: FC<Props> = ({
Fixed

2025-02-04 01:24 UTC, HenriqueLimas commented on src/ebay-skeleton/ebay-skeleton-avatar.tsx
> +import { NativeTags } from './nativeTags'
Fixed

2025-02-04 01:24 UTC, HenriqueLimas commented on src/ebay-skeleton/ebay-skeleton-button.tsx
> +    <div
Fixed

2025-02-04 01:24 UTC, HenriqueLimas commented on src/ebay-skeleton/ebay-skeleton-text.tsx
> +    <div
Fixed

2025-02-04 01:27 UTC, HenriqueLimas approved these changes

2025-02-04 01:28 UTC, HenriqueLimas commented on src/ebay-skeleton/ebay-skeleton-button.tsx
> +export type Props = ComponentProps<'div'> & {
I think it depends, we don't have a consistency yet. Both are fine

2025-02-04 01:29 UTC, HenriqueLimas commented on src/ebay-skeleton/ebay-skeleton-textbox.tsx
> +    <div
Fixed

2025-02-04 01:29 UTC, HenriqueLimas commented on src/ebay-skeleton/ebay-skeleton-image.tsx
> +    <div
Fixed

2025-02-04 01:31 UTC, HenriqueLimas requested changes
Missing the README

2025-02-04 01:44 UTC, HenriqueLimas approved these changes

2025-02-04 17:47 UTC, merged